### ISSUE TITLE
fire should gracefully handle compilation failures

### ISSUE THREAD

**Issue by modulovalue** [ykmnkmi/fire.dart#5]
When the code that is being reloaded isn't valid Dart code fire will crash and not report any error messages.

1) When code can't be compiled fire should expose the error messages that are being produced.
2) When code can't be compiled fire should not crash and exit.

A Stacktrace like this one is being thrown when fire crashes.
```
Unhandled exception:
Bad state: Expected exactly `602ff002-ed65-4145-851c-5d37f69bc08f` but got:
[...].dart: Warning: Interpreting this as package URI, '[...].dart'.
#0      FrontendServerClient.reject (package:frontend_server_client/src/frontend_server_client.dart:273:13)
<asynchronous suspension>
#1      main ([...]/fire.dart/bin/fire.dart.dart:124:3)
<asynchronous suspension>
```

**Comment by modulovalue** [comment]
I think I know why this happens:

By returning the reject invocations, the surrounding try catch is being escaped. It seems like they should be awaited inside of the try catch e.g.:
https://github.com/modulovalue/fire.dart/blob/65d5427ab25aa146baff0d0207893e72b9b27721/lib/fire.dart#L72-L75

**Comment by ykmnkmi** [comment]
Missed it, thanks. Do you plan to send a PR? I will fix this later.

**Comment by modulovalue** [comment]
See #7
